language: node_js
node_js:
- '4.0'
- '8.0'
sudo: false
deploy:
  - provider: npm
    email: tituswormer@gmail.com
    api_key:
      secure: WWCHUxJuIhbjEq6bOcCAWNuwATqpPexv77WOe08M+UCMhIIQo1FoQxrVBittoKDN2ZrAiT58/ehaTq5x3lljqvJuFACdMkVl7DqI8PDfb3Yi9XYgCt4QsZ8hr1GLpkkpsRcn/inOIME05TtNZULmrCjVKYOP7NZIwYC/5lK11H8=
    on:
      tags: true
      node: '4.0'
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: LgbEAk2VADSEeFjsuxIpuhAGT+pIntK5Zn6wjpW+TJ/EAzd2BjlO93E35EksrdGusofUi6Ygud1dm+9vbMUFFH/ZaGzzR1zXawp0Yt2FjEfxW1mzCwaXMPkUBOWoCoXdyvASnmBmpKmAXPVin18H9y1aqGnXjE1wHwalNgsqvdE=
    file:
      - "fillers.js"
      - "fillers.min.js"
    on:
      tags: true
      node: '8.0'
